name: local_storage
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/tihrasguinho/local_storage

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.2
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  checks: ^0.3.0

flutter:
